language: php

php:
  - 5.6
  - 7.0

before_script:
  - "mkdir -p ~/.composer"
  - openssl aes-256-cbc -K $encrypted_c6cd2c2aeded_key -iv $encrypted_c6cd2c2aeded_iv -in .travis.composer.config.json.enc -out ~/.composer/config.json -d
  - composer self-update
  - composer install
  - composer require satooshi/php-coveralls

script:
  - vendor/bin/phpunit --coverage-text

after_script:
  - travis_retry vendor/bin/coveralls
